const BACKEND_URL = 'http://localhost:3000'
const ACCESS_TOKEN_KEY = 'access_token'

const SEPOLIA_RPC_URL = import.meta.env.VITE_SEPOLIA_RPC_URL
const ARBITRUM_SEPOLIA_RPC_URL = import.meta.env.VITE_ARBITRUM_SEPOLIA_RPC_URL

export { BACKEND_URL, ACCESS_TOKEN_KEY, SEPOLIA_RPC_URL, ARBITRUM_SEPOLIA_RPC_URL }