// Code generated by MockGen. DO NOT EDIT.
// Source: graph/client.go

// Package graph is a generated GoMock package.
package graph

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockGraphqlClient is a mock of GraphqlClient interface.
type MockGraphqlClient struct {
	ctrl     *gomock.Controller
	recorder *MockGraphqlClientMockRecorder
}

// MockGraphqlClientMockRecorder is the mock recorder for MockGraphqlClient.
type MockGraphqlClientMockRecorder struct {
	mock *MockGraphqlClient
}

// NewMockGraphqlClient creates a new mock instance.
func NewMockGraphqlClient(ctrl *gomock.Controller) *MockGraphqlClient {
	mock := &MockGraphqlClient{ctrl: ctrl}
	mock.recorder = &MockGraphqlClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGraphqlClient) EXPECT() *MockGraphqlClientMockRecorder {
	return m.recorder
}

// QueryAgreementsForAddress mocks base method.
func (m *MockGraphqlClient) QueryAgreementsForAddress(arg0 string) ([]AgreementLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryAgreementsForAddress", arg0)
	ret0, _ := ret[0].([]AgreementLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryAgreementsForAddress indicates an expected call of QueryAgreementsForAddress.
func (mr *MockGraphqlClientMockRecorder) QueryAgreementsForAddress(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryAgreementsForAddress", reflect.TypeOf((*MockGraphqlClient)(nil).QueryAgreementsForAddress), arg0)
}
