name: Build and tag main branch


on:
  push:
    branches:
      - main
    paths:
      - 'blockchain/**'

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            submodules: recursive
        - name: Install Foundry
          uses: foundry-rs/foundry-toolchain@v1
        - name: Initialize project
          run: |
            make init-project
        - name: Build and test
          run: |
            make build
        - name: Configure version information
          uses: ./.github/workflows/common-release.yaml
          with:
            target-prefix: 'sc-'
