name: Graph - Build and test pull request

on:
  pull_request:
    branches:
      - main
    paths:
      - 'graph/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./graph
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Install Graph CLI Global (Optional)
        run: npm install -g @graphprotocol/graph-cli
      - name: Install dependencies
        run: |
          npm install
      - name: Generate Code from Schema
        run: npm run codegen
      - name: Build and test Seplia Subgraph
        run: npm run build:sepolia && npm run test
